import { type GiphyTheme } from '@giphy/react-native-sdk'

export const customThemeSample: GiphyTheme = {
  avatarPlaceholderColor: '#00695C',
  backgroundColor: '#373d48',
  backgroundColorForLoadingCells: '#0277BD',
  cellCornerRadius: 12,
  confirmationBackButtonColor: '#5294e2',
  confirmationSelectButtonColor: '#CDDC39',
  confirmationSelectButtonTextColor: '#37474F',
  confirmationViewOnGiphyColor: '#CFD8DC',
  defaultTextColor: '#B0BEC5',
  dialogOverlayBackgroundColor: 'rgba(69, 90, 100, 0.6)',
  emojiDrawerGradientBottomColor: '#9933ff',
  emojiDrawerGradientTopColor: '#5294e2',
  emojiDrawerScrollIndicatorStyle: 'light',
  emojiDrawerSeparatorColor: 'rgba(0, 0, 0, 0.2)',
  fixedSizeCells: false,
  handleBarColor: '#00ff99',
  keyboardAppearance: 'light',
  retryButtonBackgroundColor: '#CDDC39',
  retryButtonTextColor: '#37474F',
  searchBackButtonColor: '#5294e2',
  searchBarBackgroundColor: '#3e444e',
  searchBarCornerRadius: 0,
  searchBarPadding: 0,
  searchPlaceholderTextColor: '#d8d8d8',
  searchTextColor: '#fafafa',
  showSuggestionsBar: true,
  stickerBackgroundColor: 'rgba(0, 0, 0, 0.25)',
  suggestionCellBackgroundColor: 'rgba(0, 0, 0, 0.25)',
  suggestionCellTextColor: '#CFD8DC',
  tabBarBackgroundAlpha: 0.15,
  tabBarSwitchDefaultColor: '#BDBDBD',
  tabBarSwitchSelectedColor: '#CDDC39',
  usernameColor: '#FFCCBC',
}
