name: 'Build & Publish to NPM'

on:
  push:
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🏷 Set vars
        id: vars
        run: node ./scripts/pkg.release-vars.js

      - name: 🛠️ Set up environment
        uses: ./.github/actions/setup
        with:
          example-dependencies: false
          node-version: 24

      - name: 🧱 Build package
        run: yarn build

      - name: 📦 Check package contents
        run: npm pack --dry-run --ignore-scripts

      - name: 🚀 Publish to NPM
        run: npm publish --provenance --access public --tag "$NPM_TAG" --ignore-scripts
        env:
          NPM_TAG: ${{ steps.vars.outputs.npm-tag }}

      - name: 🗒 Add summary
        if: ${{ success() }}
        run: |
          echo 'RN SDK [${{ steps.vars.outputs.tag }}](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/${{ steps.vars.outputs.tag }}) released.' >> $GITHUB_STEP_SUMMARY
          echo 'Release: <https://github.com/Giphy/giphy-react-native-sdk/releases/tag/${{ steps.vars.outputs.tag }}>' >> $GITHUB_STEP_SUMMARY
          echo 'NPM: <https://www.npmjs.com/package/@giphy/react-native-sdk/v/${{ steps.vars.outputs.package-version }}>' >> $GITHUB_STEP_SUMMARY
